name: Publish Weekly Badge

on:
  workflow_dispatch:
    inputs:
      status:
        description: "Badge status"
        type: choice
        required: true
        options: [GREEN, YELLOW, RED]
        default: GREEN
      verified_date:
        description: "Verified date (2025-10-28)"
        type: string
        required: true
        default: "2025-10-28"
      certificate_url:
        description: "Link to weekly certificate PDF (or #)"
        type: string
        required: false
        default: "#"

  schedule:
    # Every Monday at 03:00 UTC
    - cron: "0 3 * * 1"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set metadata (with fallbacks for schedule)
        id: meta
        shell: bash
        run: |
          STATUS="${{ github.event.inputs.status }}"
          VERIFIED="${{ github.event.inputs.verified_date }}"
          CERT="${{ github.event.inputs.certificate_url }}"
          : "${STATUS:=GREEN}"
          : "${VERIFIED:=$(date -u +%F)}"
          : "${CERT:=#}"
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"
          echo "verified_date=$VERIFIED" >> "$GITHUB_OUTPUT"
          echo "certificate_url=$CERT" >> "$GITHUB_OUTPUT"

      - name: Update index.html (replace badge block)
        shell: bash
        run: |
          FILE="index.html"
          perl -0777 -pe 's|<script id="badge-config">[\s\S]*?</script>|<script id="badge-config">\n  window.BADGE_STATUS='\''${{ steps.meta.outputs.status }}'\'';\n  window.VERIFIED_DATE='\''${{ steps.meta.outputs.verified_date }}'\'';\n  window.CERT_URL='\''${{ steps.meta.outputs.certificate_url }}'\'';\n</script>|s' -i "$FILE"

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish badge: ${{ steps.meta.outputs.status }} / ${{ steps.meta.outputs.verified_date }}"
          branch: main
