name: Publish Weekly Badge

on:
  workflow_dispatch:
    inputs:
      status:
      verified_date:
      certificate_url:
  schedule:
    - cron: "0 3 * * 1"
  description: "Badge status"
  type: choice
  required: true
  options: [GREEN, YELLOW, RED]
  default: GREEN
description: "Verified date (YYYY-MM-DD)"
type: string 
required: true 
default: "2025-11-02"
certificate_url:
        description: "Link to weekly certificate PDF (or #)"
        type: string
        required: false
        default: "#"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set metadata
        id: meta
        run: |
          echo "status=${{ github.event.inputs.status }}" >> $GITHUB_OUTPUT
          echo "verified_date=${{ github.event.inputs.verified_date }}" >> $GITHUB_OUTPUT
          echo "certificate_url=${{ github.event.inputs.certificate_url }}" >> $GITHUB_OUTPUT

      - name: Update index.html (replace badge block)
        run: |
          FILE="index.html"
          perl -0777 -pe "s|<script id=\"badge-config\">[\\s\\S]*?</script>|<script id=\"badge-config\">\n  window.STATUS='${{ steps.meta.outputs.status }}';\n  window.VERIFIED_DATE='${{ steps.meta.outputs.verified_date }}';\n  window.CERT_URL='${{ steps.meta.outputs.certificate_url }}';\n</script>|s" -i \"$FILE\"

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish badge: ${{ steps.meta.outputs.status }} / ${{ steps.meta.outputs.verified_date }}"
          branch: main
